// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import LoadSubCategoriesController from "./load_sub_categories_controller"
application.register("load-sub-categories", LoadSubCategoriesController)

import ToggleCategoriesController from "./toggle_categories_controller"
application.register("toggle-categories", ToggleCategoriesController)
